import Head from 'next/head'
import {useRouter} from "next/router";
import {useSelector} from "react-redux";
import auth, {authSlice, selectAuthState} from "../src/store/auth";
import {useEffect} from "react";
import useTrans from "./hooks/useTrans";
export default function Home() {
    const router = useRouter()
    const authState = useSelector(selectAuthState)
    // const token = localStorage.getItem('token') || ''
    const trans = useTrans()

    useEffect(() => {
        if (!authState){
            router.push(`auth/login`)
        }
    }, [router, authState])

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                {trans.home.title}
            </main>
        </>
    )
}
