import Head from 'next/head'
import {useRouter} from "next/router";
import {useSelector} from "react-redux";
import {selectAuthState} from "../src/store/auth";
import {useEffect} from "react";
import useTrans from "./hooks/useTrans";
import {selectPostState} from "../src/store/posts";
import {Button, Card, Col, Row, Typography} from "antd";

export default function Home() {
    const router = useRouter()
    const authState = useSelector(selectAuthState)
    const postsState = useSelector(selectPostState)
    const trans = useTrans()

    useEffect(() => {
        const token = localStorage.getItem('token')
        if (!token){
            router.push(`auth/login`)
        }
    }, [])

    const toLogin = () => {
        router.push('auth/login')
    }

    const toLearn = () => {
        router.push('https://beta.reactjs.org/')
    }

    return (
        <>
            <Head>
                <title>PPA OMED</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <Row gutter={[16,24]}>
                    <Col span={12}>
                        <Card title={trans.home.title} actions={[
                            <Button key='login' type='primary' onClick={toLogin}>
                                {trans.button.login}
                            </Button>,
                            <Button key='learn' type='default' onClick={toLearn}>
                                {trans.button.learnWithMe}
                            </Button>
                        ]} style={{width: '500px', margin: '1rem'}}>
                            <Typography.Title>
                                {trans.react.thinking}
                            </Typography.Title>
                            <Typography.Paragraph>
                                {trans.react.quote}
                            </Typography.Paragraph>
                        </Card>
                    </Col>
                    <Col span={12}>
                        <Card title={trans.home.redux} style={{width: '500px', margin: '1rem'}}>
                            <pre>
                                {JSON.stringify({postSlice: postsState, authSlice: {authState: authState}}, null, 2)}
                            </pre>
                        </Card>
                    </Col>
                </Row>


            </main>
        </>
    )
}
